### ISSUE TITLE
Problems Running API

### ISSUE THREAD

**Issue by xie** [rydrman/ReactiveSpaces#1]

**Comment by rydrman** [comment]
It looks like you may have issues with your OS not being able to unzip the files. Can you confirm that you are able to open other .zip files on the PCs? I haven't been able to replicate this error yet on my end.

**Comment by hughxie** [comment]
Yes, I am able to unzip files, I have never encountered this issue before. I'll try on a new OS, maybe windows 10.

On Aug 9, 2015 11:20 PM, Ryan Bottriell <notifications@github.com> wrote:

It looks like you may have issues with your OS not being able to unzip the files. Can you confirm that you are able to open other .zip files on the PCs? I haven't been able to replicate this error yet on my end.

**Comment by rydrman** [comment]
I think first I would suggest using a different tool to unzip the file, maybe 7-zip or another 3rd party application. If nothing else we might get a more descriptive error message.

**Comment by hughxie** [comment]
Using 7-Zip, it tells me there is an "Unsupported compression method" for all the files.

On Aug 11, 2015 11:59 PM, Ryan Bottriell <notifications@github.com> wrote:

I think first I would suggest using a different tool to unzip the file, maybe 7-zip or another 3rd party application. If nothing else we might get a more descriptive error message.
